VMStateField vmstate_rtcstate[] = {
    VMSTATE_BUFFER(cmos_data, RTCState),
    VMSTATE_UINT8(cmos_index, RTCState),
    VMSTATE_INT32(current_tm.tm_sec, RTCState),
    VMSTATE_INT32(current_tm.tm_min, RTCState),
    VMSTATE_INT32(current_tm.tm_hour, RTCState),
    VMSTATE_INT32(current_tm.tm_wday, RTCState),
    VMSTATE_INT32(current_tm.tm_mday, RTCState),
    VMSTATE_INT32(current_tm.tm_mon, RTCState),
    VMSTATE_INT32(current_tm.tm_year, RTCState),
    VMSTATE_INT32(base_year, RTCState),
    VMSTATE_TIMER(periodic_timer, RTCState),
    VMSTATE_INT64(next_periodic_time, RTCState),
    VMSTATE_INT64(next_second_time, RTCState),
    VMSTATE_UINT32_V(irq_coalesced, RTCState, 2),
    VMSTATE_UINT32_V(period, RTCState, 2),
    VMSTATE_TIMER(second_timer, RTCState),
    VMSTATE_TIMER(second_timer2, RTCState),
    VMSTATE_END_OF_LIST()
};
